# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  build_and_deploy:
    docker: 
      - image: circleci/golang:1.14
    steps:
      - checkout
      - sam/install
      - sam/build:
          s3-bucket: "isolator-demo-2020-04-07"
          use-container: false
          template: template.yaml
      - run:
          name: SAM Deploy
          command: |
            sam deploy \
              --stack-name brancher-staging \
              --template .aws-sam/build/template.yaml \
              --s3-bucket isolator-demo-2020-04-07 \
              --capabilities CAPABILITY_IAM

workflows:
  staging:
    jobs:
      - build_and_deploy
